[project]
name = "tandem-fetch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Oskari Timgren", email = "oskari.timgren@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.16.5",
    "arrow>=1.3.0",
    "cryptography>=44.0.0",
    "loguru>=0.7.3",
    "polars>=1.33.0",
    "psycopg2>=2.9.10",
    "pyjwt>=2.10.1",
    "requests>=2.32.3",
    "sqlalchemy>=2.0.43",
]

[project.scripts]
tandem-fetch = "tandem_fetch:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
